# Generated by Django 4.2.13 on 2024-06-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inventory",
            name="receivedBy",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="storage",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="vendor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
