# Generated by Django 4.2.13 on 2024-06-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_order_inventory_receivedby_inventory_storage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="catelogNumber",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="orderedDate",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="vendor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
