# Generated by Django 4.2.13 on 2024-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_order_catelognumber_order_name_order_ordereddate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="receivedDate",
        ),
        migrations.AddField(
            model_name="order",
            name="staff",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
