# Generated by Django 4.2.13 on 2024-07-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_inventory_receiveddate_order_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="receivedDate",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
