# Generated by Django 4.2.13 on 2024-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_inventory_receiveddate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("quantity", models.PositiveBigIntegerField(null=True)),
                ("catelogNumber", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
