# Generated by Django 4.2.13 on 2024-07-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_inventory_name_alter_order_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="vendor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
