# Generated by Django 4.2.13 on 2024-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_request_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organism", models.CharField(max_length=100, null=True)),
                ("idNumber", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("isolationSource", models.CharField(max_length=300, null=True)),
                ("alternateDesignation", models.CharField(max_length=300, null=True)),
                ("receivedFrom", models.CharField(max_length=300, null=True)),
                ("ReceivedDate", models.DateField(null=True)),
                ("originallyReceivedFrom", models.CharField(max_length=300, null=True)),
                ("additionalInfo", models.TextField(null=True)),
            ],
        ),
    ]
