# Generated by Django 4.2.13 on 2024-07-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_culture"),
    ]

    operations = [
        migrations.AddField(
            model_name="culture",
            name="boxNumber",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
