# Generated by Django 4.2.13 on 2024-07-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_culture_boxnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="culture",
            name="copySaved",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
